# See https://github.com/returntocorp/semgrep/issues/2438
rules:
  - id: found-settings-file
    message: Detected a Potential Django settings.py file
    severity: INFO
    languages:
      - python
    # This pattern creates one finding with no text for settings.py file.
    pattern-regex: ^
    paths:
      include:
        - settings.py
